import { useState, useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import { ArrowLeft, RefreshCw, Download, AlertCircle, Loader2, TrendingUp, AlertTriangle, Target, CheckCircle, Clock, BarChart3, Brain } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import rehypeSanitize from 'rehype-sanitize'
import { reportApi } from '../services/api'
import LazyChart from '../components/LazyChart'
import type { ReportResponse } from '../types/api'

const markdownComponents = {
  h1: ({children}: any) => <h1 className="text-xl font-bold text-primary-50 mb-2">{children}</h1>,
  h2: ({children}: any) => <h2 className="text-lg font-semibold text-primary-100 mb-2">{children}</h2>,
  h3: ({children}: any) => <h3 className="text-base font-semibold text-primary-200 mb-1">{children}</h3>,
  p: ({children}: any) => <p className="text-sm text-primary-200 leading-relaxed mb-2">{children}</p>,
  ul: ({children}: any) => <ul className="list-disc list-inside text-sm text-primary-200 mb-2 space-y-1">{children}</ul>,
  ol: ({children}: any) => <ol className="list-decimal list-inside text-sm text-primary-200 mb-2 space-y-1">{children}</ol>,
  li: ({children}: any) => <li className="text-primary-200">{children}</li>,
  strong: ({children}: any) => <strong className="font-semibold text-primary-100">{children}</strong>,
  em: ({children}: any) => <em className="italic text-primary-300">{children}</em>,
  table: ({children}: any) => <table className="w-full text-sm border-collapse mb-4">{children}</table>,
  th: ({children}: any) => <th className="border border-dark-border px-3 py-2 text-left text-primary-200 bg-dark-card">{children}</th>,
  td: ({children}: any) => <td className="border border-dark-border px-3 py-2 text-primary-300">{children}</td>,
  code: ({children}: any) => <code className="bg-dark-card px-1 py-0.5 rounded text-xs text-primary-300 font-mono">{children}</code>,
  hr: () => <hr className="border-dark-border my-4" />,
}

export default function Report() {
  const { taskId } = useParams<{ taskId: string }>()
  const [report, setReport] = useState<ReportResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const controller = new AbortController()
    if (taskId) fetchReport(taskId, controller.signal)
    return () => controller.abort()
  }, [taskId])

  const fetchReport = async (id: string, signal?: AbortSignal) => {
    try {
      setLoading(true)
      setError(null)
      setReport(null)
      const data = await reportApi.get(id, { signal })
      setReport(data)
    } catch (err: any) {
      if (err.name === 'AbortError' || err.code === 'ERR_CANCELED') return
      setError(err.message || 'Failed to fetch report')
    } finally {
      setLoading(false)
    }
  }

  const handleRefresh = () => { if (taskId) fetchReport(taskId) }

  const handleDownload = () => {
    if (!report) return
    const content = `# ${report.report_title || 'Financial Research Report'}

## Executive Summary
${report.summary || 'No summary available'}

## Key Findings
${report.key_findings?.map((f: string, i: number) => `${i + 1}. ${f}`).join('\n') || 'No findings'}

## Risk Factors
${report.risk_factors?.map((r: any) => `- **${r.factor}** [${r.severity}]: ${r.description}`).join('\n') || 'No risk factors'}

## Market Trends
${report.market_trends?.map((t: string) => `- ${t}`).join('\n') || 'No trends'}

## Recommendations
${report.recommendations?.map((r: string, i: number) => `${i + 1}. ${r}`).join('\n') || 'No recommendations'}

---
Generated by Smart Finance Agent
Confidence: ${report.confidence ? `${(report.confidence * 100).toFixed(1)}%` : 'N/A'}
`
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `report-${taskId}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link to="/" className="flex items-center gap-2 text-primary-400 hover:text-primary-200 transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-primary-50">Research Report</h1>
            <p className="text-sm text-primary-400 mt-1">Task ID: {taskId}</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={handleRefresh} className="flex items-center gap-2 text-sm text-primary-400 hover:text-primary-200">
            <RefreshCw className="w-4 h-4" /> Refresh
          </button>
          <button onClick={handleDownload} disabled={!report} className="flex items-center gap-2 text-sm text-primary-400 hover:text-primary-200 disabled:opacity-50">
            <Download className="w-4 h-4" /> Download
          </button>
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="card border-red-500/30">
          <div className="flex items-center gap-3">
            <AlertCircle className="w-5 h-5 text-red-500" />
            <div>
              <p className="text-sm font-medium text-red-500">加载失败</p>
              <p className="text-xs text-red-400 mt-1">{error}</p>
            </div>
          </div>
          <button onClick={handleRefresh} className="mt-3 text-sm text-red-500 hover:text-red-400">重试</button>
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="card">
          <div className="flex items-center justify-center py-12">
            <Loader2 className="w-8 h-8 text-primary-500 animate-spin mr-3" />
            <p className="text-primary-400">加载报告中...</p>
          </div>
        </div>
      )}

      {/* Report Content */}
      {!loading && report && <ReportContent report={report} />}
    </div>
  )
}

function ReportContent({ report }: { report: any }) {
  return (
    <>
      {/* Title & Stats */}
      <div className="card">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-xl font-bold text-primary-50">{report.report_title || 'Financial Research Report'}</h2>
            <p className="text-sm text-primary-400 mt-1">AI-Powered Multi-Agent Financial Analysis</p>
          </div>
          <div className="flex items-center gap-1 px-3 py-1.5 bg-green-500/10 rounded-full">
            <CheckCircle className="w-4 h-4 text-green-500" />
            <span className="text-xs font-semibold text-green-500">Complete</span>
          </div>
        </div>
        <div className="grid grid-cols-4 gap-4">
          <div className="p-3 bg-dark-bg rounded-lg border border-dark-border">
            <p className="text-xs text-primary-400 uppercase mb-1">Tasks</p>
            <p className="text-2xl font-bold text-primary-50">{report.total_tasks || 0}</p>
          </div>
          <div className="p-3 bg-dark-bg rounded-lg border border-dark-border">
            <p className="text-xs text-green-400 uppercase mb-1">Success</p>
            <p className="text-2xl font-bold text-green-500">{report.success_tasks || 0}</p>
          </div>
          <div className="p-3 bg-dark-bg rounded-lg border border-dark-border">
            <p className="text-xs text-red-400 uppercase mb-1">Failed</p>
            <p className="text-2xl font-bold text-red-500">{report.failed_tasks || 0}</p>
          </div>
          <div className="p-3 bg-dark-bg rounded-lg border border-dark-border">
            <p className="text-xs text-primary-400 uppercase mb-1">Confidence</p>
            <p className="text-2xl font-bold text-primary-50">{report.confidence ? `${(report.confidence * 100).toFixed(1)}%` : '-'}</p>
          </div>
        </div>
      </div>

      {/* Answer - Markdown Rendering */}
      {report.answer && (
        <div className="card">
          <h3 className="text-lg font-semibold text-primary-50 mb-3">
            <Brain className="w-5 h-5 inline mr-2 text-blue-500" />
            分析结果
          </h3>
          <div className="bg-dark-bg rounded-lg p-4 border border-dark-border max-h-[600px] overflow-y-auto">
            <ReactMarkdown rehypePlugins={[rehypeSanitize]} components={markdownComponents}>
              {report.answer}
            </ReactMarkdown>
          </div>
        </div>
      )}

      {/* Key Findings */}
      {report.key_findings && report.key_findings.length > 0 && (
        <div className="card">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="w-5 h-5 text-blue-500" />
            <h3 className="text-lg font-semibold text-primary-50">Key Findings</h3>
          </div>
          <div className="space-y-3">
            {report.key_findings.map((finding: string, i: number) => (
              <div key={i} className="flex items-start gap-3 p-3 bg-dark-bg rounded-lg border border-dark-border">
                <div className="w-6 h-6 bg-blue-500/10 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                  <span className="text-xs font-bold text-blue-500">{i + 1}</span>
                </div>
                <p className="text-sm text-primary-200">{finding}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Risk Factors */}
      {report.risk_factors && report.risk_factors.length > 0 && (
        <div className="card">
          <div className="flex items-center gap-2 mb-4">
            <AlertTriangle className="w-5 h-5 text-red-500" />
            <h3 className="text-lg font-semibold text-primary-50">Risk Factors</h3>
          </div>
          <div className="space-y-3">
            {report.risk_factors.map((risk: any, i: number) => (
              <div key={i} className="p-3 bg-dark-bg rounded-lg border border-dark-border">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-sm font-semibold text-primary-200">{risk.factor}</p>
                  <span className={`badge ${risk.severity === 'high' ? 'badge-error' : risk.severity === 'medium' ? 'badge-pending' : 'badge-success'}`}>
                    {risk.severity?.toUpperCase()}
                  </span>
                </div>
                <p className="text-xs text-primary-400">{risk.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Market Trends */}
      {report.market_trends && report.market_trends.length > 0 && (
        <div className="card">
          <div className="flex items-center gap-2 mb-4">
            <BarChart3 className="w-5 h-5 text-purple-500" />
            <h3 className="text-lg font-semibold text-primary-50">Market Trends</h3>
          </div>
          <div className="space-y-2">
            {report.market_trends.map((trend: string, i: number) => (
              <div key={i} className="flex items-center gap-2 p-2 bg-dark-bg rounded-lg border border-dark-border">
                <div className="w-2 h-2 bg-purple-500 rounded-full" />
                <p className="text-sm text-primary-200">{trend}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Charts - Lazy Loaded with IntersectionObserver */}
      {report.chart_specs && report.chart_specs.length > 0 && (
        <div className="card">
          <div className="flex items-center gap-2 mb-4">
            <BarChart3 className="w-5 h-5 text-cyan-500" />
            <h3 className="text-lg font-semibold text-primary-50">Data Visualizations</h3>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {report.chart_specs.map((chart: any, index: number) => (
              <div key={index} className="bg-dark-bg rounded-lg p-4 border border-dark-border">
                <LazyChart
                  labels={chart.data?.map((d: any) => d.label) || []}
                  values={chart.data?.map((d: any) => d.value) || []}
                  title={chart.title}
                  type={chart.chart_type === 'line' ? 'line' : 'bar'}
                />
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Recommendations */}
      {report.recommendations && report.recommendations.length > 0 && (
        <div className="card">
          <div className="flex items-center gap-2 mb-4">
            <Target className="w-5 h-5 text-green-500" />
            <h3 className="text-lg font-semibold text-primary-50">Recommendations</h3>
          </div>
          <div className="space-y-3">
            {report.recommendations.map((rec: string, i: number) => (
              <div key={i} className="flex items-start gap-3 p-3 bg-dark-bg rounded-lg border border-dark-border">
                <CheckCircle className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                <p className="text-sm text-primary-200">{rec}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Execution Summary */}
      <div className="card">
        <h3 className="text-lg font-semibold text-primary-50 mb-4">Execution Summary</h3>
        <div className="grid grid-cols-2 gap-4">
          <div className="flex items-center gap-3 p-3 bg-dark-bg rounded-lg border border-dark-border">
            <Clock className="w-5 h-5 text-primary-400" />
            <div>
              <p className="text-xs text-primary-400">Duration</p>
              <p className="text-sm font-semibold text-primary-200">{report.elapsed ? `${report.elapsed.toFixed(1)}s` : '-'}</p>
            </div>
          </div>
          <div className="flex items-center gap-3 p-3 bg-dark-bg rounded-lg border border-dark-border">
            <BarChart3 className="w-5 h-5 text-primary-400" />
            <div>
              <p className="text-xs text-primary-400">Success Rate</p>
              <p className="text-sm font-semibold text-primary-200">
                {report.total_tasks ? `${((report.success_tasks || 0) / report.total_tasks * 100).toFixed(1)}%` : '-'}
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
