import { useState, useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import { 
  ArrowLeft, 
  RefreshCw, 
  Download,
  Share2,
  AlertCircle
} from 'lucide-react'
import ReportPanel from '../components/ReportPanel'
import { reportApi } from '../services/api'

export default function Report() {
  const { taskId } = useParams<{ taskId: string }>()
  const [report, setReport] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (taskId) {
      fetchReport(taskId)
    }
  }, [taskId])

  const fetchReport = async (id: string) => {
    try {
      setLoading(true)
      setError(null)
      const data = await reportApi.get(id)
      setReport(data)
    } catch (err: any) {
      setError(err.message || 'Failed to fetch report')
    } finally {
      setLoading(false)
    }
  }

  const handleRefresh = () => {
    if (taskId) {
      fetchReport(taskId)
    }
  }

  const handleDownload = () => {
    if (!report) return
    
    // Create markdown content
    const content = `# ${report.report_title || 'Financial Research Report'}

## Executive Summary
${report.summary || 'No summary available'}

## Key Findings
${report.key_findings?.map((f: string, i: number) => `${i + 1}. ${f}`).join('\n') || 'No findings'}

## Risk Factors
${report.risk_factors?.map((r: any) => `- **${r.factor}** [${r.severity}]: ${r.description}`).join('\n') || 'No risk factors'}

## Market Trends
${report.market_trends?.map((t: string) => `- ${t}`).join('\n') || 'No trends'}

## Recommendations
${report.recommendations?.map((r: string, i: number) => `${i + 1}. ${r}`).join('\n') || 'No recommendations'}

---
Generated by Smart Finance Agent
Confidence: ${report.confidence ? `${(report.confidence * 100).toFixed(1)}%` : 'N/A'}
`

    // Create download link
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `report-${taskId}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link
            to="/"
            className="flex items-center gap-2 text-primary-400 hover:text-primary-200 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-primary-50">Research Report</h1>
            <p className="text-sm text-primary-400 mt-1">
              Task ID: {taskId}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handleRefresh}
            className="flex items-center gap-2 text-sm text-primary-400 hover:text-primary-200 transition-colors"
          >
            <RefreshCw className="w-4 h-4" />
            Refresh
          </button>
          <button
            onClick={handleDownload}
            disabled={!report}
            className="flex items-center gap-2 text-sm text-primary-400 hover:text-primary-200 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Download className="w-4 h-4" />
            Download
          </button>
          <button className="flex items-center gap-2 text-sm text-primary-400 hover:text-primary-200 transition-colors">
            <Share2 className="w-4 h-4" />
            Share
          </button>
        </div>
      </div>

      {/* Error Display */}
      {error && (
        <div className="card border-red-500/30">
          <div className="flex items-center gap-3">
            <AlertCircle className="w-5 h-5 text-red-500" />
            <div>
              <p className="text-sm font-medium text-red-500">Failed to load report</p>
              <p className="text-xs text-red-400 mt-1">{error}</p>
            </div>
          </div>
          <button
            onClick={handleRefresh}
            className="mt-3 text-sm text-red-500 hover:text-red-400"
          >
            Try again
          </button>
        </div>
      )}

      {/* Report Content */}
      <ReportPanel report={report} loading={loading} />
    </div>
  )
}