import { useState, useCallback } from 'react'
import { Download, Loader2, FileText, CheckCircle } from 'lucide-react'
import { useTranslation } from 'react-i18next'

interface ReportData {
  title: string
  summary?: string
  key_findings?: string[]
  risk_factors?: Array<{ factor: string; severity: string; description: string }>
  market_trends?: string[]
  recommendations?: string[]
  answer?: string
  confidence?: number
  total_tasks?: number
  success_tasks?: number
  failed_tasks?: number
}

interface PDFExportProps {
  data: ReportData
  taskId?: string
  variant?: 'button' | 'icon'
}

export default function PDFExport({ data, taskId, variant = 'button' }: PDFExportProps) {
  const { t } = useTranslation()
  const [isExporting, setIsExporting] = useState(false)
  const [exported, setExported] = useState(false)

  const escapeHtml = useCallback((str: string): string => {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;')
  }, [])

  const generateHTML = useCallback((data: ReportData): string => {
    const safeTitle = escapeHtml(data.title || 'Financial Research Report')
    const safeAnswer = data.answer ? escapeHtml(data.answer) : ''
    const safeSummary = data.summary ? escapeHtml(data.summary) : ''
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${safeTitle}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid #e5e7eb;
    }
    h1 { font-size: 24px; color: #111827; margin-bottom: 8px; }
    .subtitle { color: #6b7280; font-size: 14px; }
    .stats {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 16px;
      margin: 24px 0;
    }
    .stat-card {
      background: #f9fafb;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 16px;
      text-align: center;
    }
    .stat-label { font-size: 12px; color: #6b7280; text-transform: uppercase; }
    .stat-value { font-size: 24px; font-weight: bold; color: #111827; margin-top: 4px; }
    h2 {
      font-size: 18px;
      color: #111827;
      margin: 32px 0 16px;
      padding-bottom: 8px;
      border-bottom: 1px solid #e5e7eb;
    }
    .finding, .recommendation {
      display: flex;
      gap: 12px;
      margin-bottom: 12px;
      padding: 12px;
      background: #f9fafb;
      border-radius: 8px;
    }
    .number {
      width: 24px;
      height: 24px;
      background: #3b82f6;
      color: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 12px;
      font-weight: bold;
      flex-shrink: 0;
    }
    .risk-item {
      padding: 12px;
      background: #fef2f2;
      border: 1px solid #fecaca;
      border-radius: 8px;
      margin-bottom: 12px;
    }
    .risk-header { display: flex; justify-content: space-between; margin-bottom: 8px; }
    .risk-factor { font-weight: 600; }
    .severity {
      font-size: 12px;
      padding: 2px 8px;
      border-radius: 12px;
      text-transform: uppercase;
    }
    .severity-high { background: #fecaca; color: #dc2626; }
    .severity-medium { background: #fef3c7; color: #d97706; }
    .severity-low { background: #d1fae5; color: #059669; }
    .trend-item {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 8px 0;
      border-bottom: 1px solid #f3f4f6;
    }
    .trend-dot { width: 8px; height: 8px; background: #5b9dff; border-radius: 50%; }
    .answer {
      background: #f9fafb;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 20px;
      white-space: pre-wrap;
      font-size: 14px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #6b7280;
      font-size: 12px;
    }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${safeTitle}</h1>
    <p class="subtitle">Generated by Smart Finance Agent</p>
  </div>

  <div class="stats">
    <div class="stat-card">
      <div class="stat-label">Total Tasks</div>
      <div class="stat-value">${data.total_tasks || 0}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Completed</div>
      <div class="stat-value">${data.success_tasks || 0}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Failed</div>
      <div class="stat-value">${data.failed_tasks || 0}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Confidence</div>
      <div class="stat-value">${data.confidence ? `${(data.confidence * 100).toFixed(1)}%` : '-'}</div>
    </div>
  </div>

  ${data.answer ? `
  <h2>Analysis Results</h2>
  <div class="answer">${safeAnswer}</div>
  ` : ''}

  ${data.summary ? `
  <h2>Executive Summary</h2>
  <p>${safeSummary}</p>
  ` : ''}

  ${data.key_findings && data.key_findings.length > 0 ? `
  <h2>Key Findings</h2>
  ${data.key_findings.map((finding, i) => `
    <div class="finding">
      <div class="number">${i + 1}</div>
      <p>${escapeHtml(finding)}</p>
    </div>
  `).join('')}
  ` : ''}

  ${data.risk_factors && data.risk_factors.length > 0 ? `
  <h2>Risk Factors</h2>
  ${data.risk_factors.map(risk => `
    <div class="risk-item">
      <div class="risk-header">
        <span class="risk-factor">${escapeHtml(risk.factor)}</span>
        <span class="severity severity-${escapeHtml(risk.severity)}">${escapeHtml(risk.severity)}</span>
      </div>
      <p style="font-size: 14px; color: #6b7280;">${escapeHtml(risk.description)}</p>
    </div>
  `).join('')}
  ` : ''}

  ${data.market_trends && data.market_trends.length > 0 ? `
  <h2>Market Trends</h2>
  ${data.market_trends.map(trend => `
    <div class="trend-item">
      <div class="trend-dot"></div>
      <p>${escapeHtml(trend)}</p>
    </div>
  `).join('')}
  ` : ''}

  ${data.recommendations && data.recommendations.length > 0 ? `
  <h2>Recommendations</h2>
  ${data.recommendations.map((rec, i) => `
    <div class="recommendation">
      <div class="number">${i + 1}</div>
      <p>${escapeHtml(rec)}</p>
    </div>
  `).join('')}
  ` : ''}

  <div class="footer">
    <p>Report ID: ${taskId || 'N/A'} | Generated: ${new Date().toLocaleString()}</p>
    <p>Smart Finance Agent - AI-Powered Financial Research</p>
  </div>
</body>
</html>
    `
  }, [taskId, escapeHtml])

  const handleExport = useCallback(async () => {
    setIsExporting(true)

    try {
      const html = generateHTML(data)
      const blob = new Blob([html], { type: 'text/html' })
      const url = URL.createObjectURL(blob)

      const printWindow = window.open(url, '_blank')
      if (printWindow) {
        printWindow.onload = () => {
          printWindow.print()
        }
      }

      setExported(true)
      setTimeout(() => setExported(false), 3000)
    } catch (error) {
      console.error('Export failed:', error)
    } finally {
      setIsExporting(false)
    }
  }, [data, generateHTML])

  if (variant === 'icon') {
    return (
      <button
        onClick={handleExport}
        disabled={isExporting}
        className="p-2 text-primary-400 hover:text-primary-200 hover:bg-dark-card rounded-lg transition-colors"
        title={t('report.download')}
      >
        {isExporting ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : exported ? (
          <CheckCircle className="w-4 h-4 text-green-500" />
        ) : (
          <Download className="w-4 h-4" />
        )}
      </button>
    )
  }

  return (
    <button
      onClick={handleExport}
      disabled={isExporting}
      className="btn-secondary flex items-center gap-2"
    >
      {isExporting ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          {t('common.loading')}
        </>
      ) : exported ? (
        <>
          <CheckCircle className="w-4 h-4 text-green-500" />
          {t('common.success')}
        </>
      ) : (
        <>
          <FileText className="w-4 h-4" />
          {t('report.download')} PDF
        </>
      )}
    </button>
  )
}
